modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20No%20Feather%20Trample"
logoFile="icon.png"

[[mods]]
modId="nofeathertrample"
version="1.2"
displayName="No Feather Trample"
displayURL="https://serilum.com/mod/no-feather-trample"
authors="Rick South"
description='''Prevents farm land from being trampled while wearing Feather Falling or having the Slow Falling effect.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jeremy Langford, Michael W. S., Rare Students, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.nofeathertrample]]
    modId="collective"
    mandatory=true
    versionRange="[7.61,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nofeathertrample]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21]"
    ordering="NONE"
    side="BOTH"
